GET http://localhost:3001/persons

###
GET http://localhost:3001/persons/1

###

POST http://localhost:3001/persons HTTP/1.1
content-type: application/json

{
    "name": "test",
    "number": 123
}
###
DELETE http://localhost:3001/persons/5